"""add tip_percent and confirmed to session_members

Revision ID: 156dac2499c0
Revises: 254284816472
Create Date: 2026-02-16 21:10:22.851335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156dac2499c0'
down_revision: Union[str, Sequence[str], None] = '254284816472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_members', sa.Column('tip_percent', sa.Integer(), nullable=True))
    op.add_column('session_members', sa.Column('confirmed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_members', 'confirmed')
    op.drop_column('session_members', 'tip_percent')
    # ### end Alembic commands ###
