"""add paid_scans to user_quotas

Revision ID: 254284816472
Revises: bea57eb4c49e
Create Date: 2026-02-16 20:04:22.848346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '254284816472'
down_revision: Union[str, Sequence[str], None] = 'bea57eb4c49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quotas', sa.Column('paid_scans', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_quotas', 'paid_scans')
    # ### end Alembic commands ###
