"""add quantity to item_votes

Revision ID: 4eb5c3f19b63
Revises: 156dac2499c0
Create Date: 2026-02-16 21:29:58.157125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5c3f19b63'
down_revision: Union[str, Sequence[str], None] = '156dac2499c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_votes', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_votes', 'quantity')
    # ### end Alembic commands ###
